services:
  broadcast-emitter:
    image: java-udp-programming
    build:
      context: .
    command:
      - TODO

  multicast-emitter:
    image: java-udp-programming
    build:
      context: .
    command:
      - TODO

  unicast-emitter:
    image: java-udp-programming
    build:
      context: .
    command:
      - TODO

  broadcast-receiver-1:
    image: java-udp-programming
    build:
      context: .
    command:
      - TODO
    depends_on:
      - broadcast-emitter

  broadcast-receiver-2:
    image: java-udp-programming
    build:
      context: .
    command:
      - TODO
    depends_on:
      - broadcast-emitter

  unicast-receiver-1:
    image: java-udp-programming
    build:
      context: .
    command:
      - TODO
    depends_on:
      - unicast-emitter

  unicast-receiver-2:
    image: java-udp-programming
    build:
      context: .
    command:
      - TODO
    depends_on:
      - unicast-emitter

  multicast-receiver-1:
    image: java-udp-programming
    build:
      context: .
    command:
      - TODO
    depends_on:
      - multicast-emitter

  multicast-receiver-2:
    image: java-udp-programming
    build:
      context: .
    command:
      - TODO
    depends_on:
      - multicast-emitter

  multicast-receiver-3:
    image: java-udp-programming
    build:
      context: .
    command:
      - TODO
    depends_on:
      - multicast-emitter
