networks:
  my-isolated-network:
    name: my-isolated-network-name

services:
  broadcast-emitter:
    image: java-udp-programming
    build:
      context: .
    command:
      - broadcast-emitter
      - --delay=5000
      - --frequency=30000
      - --host=255.255.255.255
      - --port=9876
    networks:
      - my-isolated-network

  multicast-emitter:
    image: java-udp-programming
    build:
      context: .
    command:
      - multicast-emitter
      - --delay=10000
      - --frequency=15000
      - --host=239.1.1.1
      - --port=9876
      - --interface=eth0

  unicast-emitter:
    image: java-udp-programming
    build:
      context: .
    command:
      - unicast-emitter
      - --delay=10000
      - --frequency=15000
      - --host=unicast-receiver-1
      - --port=9876

  broadcast-receiver-1:
    image: java-udp-programming
    build:
      context: .
    command:
      - broadcast-receiver
      - --port=9876
    networks:
      - my-isolated-network
    depends_on:
      - broadcast-emitter

  broadcast-receiver-2:
    image: java-udp-programming
    build:
      context: .
    command:
      - broadcast-receiver
      - --port=9876
    networks:
      - my-isolated-network
    depends_on:
      - broadcast-emitter

  unicast-receiver-1:
    image: java-udp-programming
    build:
      context: .
    command:
      - unicast-receiver
      - --port=9876
    depends_on:
      - unicast-emitter

  unicast-receiver-2:
    image: java-udp-programming
    build:
      context: .
    command:
      - unicast-receiver
      - --port=9876
    depends_on:
      - unicast-emitter

  multicast-receiver-1:
    image: java-udp-programming
    build:
      context: .
    command:
      - multicast-receiver
      - --host=239.1.1.1
      - --port=9876
      - --interface=eth0
    depends_on:
      - multicast-emitter

  multicast-receiver-2:
    image: java-udp-programming
    build:
      context: .
    command:
      - multicast-receiver
      - --host=239.1.1.1
      - --port=9876
      - --interface=eth0
    depends_on:
      - multicast-emitter

  multicast-receiver-3:
    image: java-udp-programming
    build:
      context: .
    command:
      - multicast-receiver
      - --host=239.1.1.2
      - --port=9876
      - --interface=eth0
    depends_on:
      - multicast-emitter
